### ISSUE TITLE
Radio buttons for source selection

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/project-website#19]
Selection does not work, if I click on the text (Pubmed vs DOAJ). Only clicking the radio buttons (circles) works

**Comment by Bubblbu** [comment]
Apparently the selection of the labels is at the moment not synced with the selection of the actual buttons.

e.g. ff I click and select "PubMed", visually the label switches to "selected" but the radio button itself doesn't react.

**Comment by tanteuschi** [comment]
This happens because on "Pubmed (respectively DOAJ)" is a hover link with the discription of the library.. this disables the possibility to make the selection by clicking on "Pubmed (respectively DOAJ)". I have solved this issues with an info button in the upcoming new and improved version of the website.
